#!/bin/bash
#
#

INPUT="$@"

for i in $INPUT;
do
    STRING=`cat $i`
    Rscript ~/bin/motifme.R $STRING
    paste -d' ' A.txt H.txt P.txt | awk '{gsub(/\[\[[0-9]+\]\]/,"");}{gsub(/\[1\]/,"");}1' | awk 'NF' > hold1.txt
    rm A.txt H.txt P.txt
#    awk '{if (  ($10 == 0 | $11 == 0) &&
#                ($
#                ($1 >= 3 || $2 >= 3)
                
            
done

exit
